baseURL = "https://my.tyihan.com/"
languageCode = "zh-CN"
title = "田一含"

[params]
  description = "终身学习者"
  author = "田一含"
  since = "2025年5月18日"
  school = "中国人民大学"
  major = "金融学"
  location = "北京"
  wechat = "Elowen Tian"
  email = "tianyihan498@gmail.com"
  github = "yihan498"

[menu]
  [[menu.main]]
    name = "文章"
    url = "/articles/"
    weight = 1
  [[menu.main]]
    name = "成长"
    url = "/growth/"
    weight = 2
  [[menu.main]]
    name = "项目"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "联系"
    url = "/contact/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
